---
# Clojure default vars.
# Can be overridden in the call to the role.
clojure_version: "1.10.1.507" # until an apt package is available
clojure_sha256: "sha256:206fce67ca550fc51a3903937b0fbaeb4bbacb1788c5a0886523ba2e60f06dde"
