---
# Clojure default vars.
# Can be overridden in the call to the role.
clojure_version: "1.10.1.447" # until an apt package is available
clojure_sha256: "sha256:a3fca4a7be0fe740508a913bd943d5dacae81f984e105099a228e2615c5ab0bb"
